//! Tests for the NEB band reader, against the REAL Menshutkin NEB-TS probe artifacts
//! (`tests/fixtures/neb/`, 2026-08-10) — the run that recovered the known saddle.

use std::path::{Path, PathBuf};

use super::{parse_final_interp, parse_neb_log, NebBand};
use crate::parse::{derived_identity_ids, ParseError, ReferenceGeometry};

const NEB_LOG: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/neb/input.NEB.log"
));
const FINAL_INTERP: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/neb/input.final.interp"
));

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/neb")
}

/// Reactant element order for the 15-atom Menshutkin system (C N H×5 C C I H×5).
/// Matches the converged-TS xyz element sequence. Coords are dummy — the TS
/// element-order post-condition consults only `z`.
fn reference() -> ReferenceGeometry {
    let z = vec![6u8, 7, 1, 1, 1, 1, 1, 6, 6, 53, 1, 1, 1, 1, 1];
    let ids = derived_identity_ids(z.len());
    ReferenceGeometry { z, xyz_angstrom: vec![[0.0; 3]; 15], ids }
}

const BOHR_TO_ANGSTROM: f64 = 0.529_177_210_903;

#[test]
fn parses_the_real_per_iteration_band() {
    let its = parse_neb_log(NEB_LOG).expect("real NEB.log parses");
    assert_eq!(its.len(), 24, "24 iterations (0..23)");
    for it in &its {
        assert_eq!(it.images.len(), 10, "NImages 8 → 10 images every iteration");
    }
    // First image of iteration 0 is the reactant end (arc length 0).
    assert!(its[0].images[0].distance_angstrom.abs() < 1e-9);
    // Second image: 0.63257303 Bohr → Å.
    assert!((its[0].images[1].distance_angstrom - 0.63257303 * BOHR_TO_ANGSTROM).abs() < 1e-6);
    // Energies are ABSOLUTE Eh (reactant end ≈ −472.768).
    assert!((its[0].images[0].energy_eh - (-472.76823633)).abs() < 1e-6);
    // Final converged barrier ≈ 0.01555 Eh (the known value).
    assert!((its[23].barrier_eh - 0.01555408).abs() < 1e-6, "{}", its[23].barrier_eh);
}

#[test]
fn climbing_image_appears_only_once_climbing_is_on() {
    let its = parse_neb_log(NEB_LOG).unwrap();
    // Iteration 0: `climbing : no` → no climbing image yet.
    assert_eq!(its[0].climbing_image, None);
    // Final iteration: `climbing : yes`, barrier `(image: 5)`.
    assert_eq!(its[23].climbing_image, Some(5));
}

#[test]
fn parses_the_smooth_mep_relative_energies() {
    let mep = parse_final_interp(FINAL_INTERP).expect("real final.interp parses");
    assert!(mep.len() > 20, "the smooth MEP has many rows, got {}", mep.len());
    // Interp energies are RELATIVE — image 0 = 0.
    assert!(mep[0].distance_angstrom.abs() < 1e-9);
    assert!(mep[0].energy_eh.abs() < 1e-9);
    // Distances are Bohr→Å and monotonic non-decreasing.
    for w in mep.windows(2) {
        assert!(w[1].distance_angstrom >= w[0].distance_angstrom);
    }
}

#[test]
fn from_path_verify_recovers_the_known_saddle() {
    let band = NebBand::from_path(&fixtures_dir())
        .expect("read ok")
        .expect("NEB.log present → Some");
    let v = band.verify(&reference(), 10).expect("post-conditions pass");
    // The converged TS geometry recovers the known SN2 saddle: N(1)···C(8) ≈ 2.353 Å.
    let (_els, xyz) = v.ts_geometry();
    let d = |i: usize, j: usize| {
        ((xyz[i][0] - xyz[j][0]).powi(2)
            + (xyz[i][1] - xyz[j][1]).powi(2)
            + (xyz[i][2] - xyz[j][2]).powi(2))
        .sqrt()
    };
    assert!((d(1, 8) - 2.353).abs() < 0.01, "N···C = {}", d(1, 8));
    assert!((d(8, 9) - 2.594).abs() < 0.01, "C···I = {}", d(8, 9));
    assert!((v.final_barrier_eh().unwrap() - 0.01555408).abs() < 1e-6);
    assert_eq!(v.iterations().len(), 24);
}

#[test]
fn absent_neb_log_is_a_normal_state() {
    // A dir with no input.NEB.log (non-NEB job) → Ok(None), not an error.
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    assert!(NebBand::from_path(&dir).unwrap().is_none());
}

// --- negative controls (rule #9: honest error, never a silent partial band) ------ //

#[test]
fn a_ragged_log_is_an_honest_error_not_a_partial_band() {
    // distance array (3) longer than energy array (2) → a loud LengthMismatch. BITE:
    // a silent zip would emit a 2-image band and hide the truncation.
    let ragged = "\
NEB log file generated by ORCA
iteration       : 0
climbing        : no
nim             : 3
barrier         :   0.01000000 (image:  1)
distance        :   0.00000000    1.00000000    2.00000000
energy          : -1.00000000   -0.90000000
>
";
    match parse_neb_log(ragged) {
        Err(ParseError::LengthMismatch { .. }) => {}
        other => panic!("expected LengthMismatch, got {other:?}"),
    }
}

#[test]
fn wrong_image_count_fails_verify() {
    // NImages+2 = 8 claimed, but the band has 10 → LengthMismatch (the NImages+2 gate).
    let band = NebBand::from_path(&fixtures_dir()).unwrap().unwrap();
    match band.verify(&reference(), 8) {
        Err(ParseError::LengthMismatch { .. }) => {}
        other => panic!("expected LengthMismatch, got {other:?}"),
    }
}

#[test]
fn wrong_ts_atom_order_is_rejected() {
    // Swap two non-equivalent elements in the reference (C↔N) → the converged TS's
    // element order no longer matches → OrderMismatch (physics on the wrong atoms).
    let band = NebBand::from_path(&fixtures_dir()).unwrap().unwrap();
    let mut r = reference();
    r.z.swap(0, 1); // C↔N
    match band.verify(&r, 10) {
        Err(ParseError::OrderMismatch { .. }) => {}
        other => panic!("expected OrderMismatch, got {other:?}"),
    }
}
